script: true
install: true
language: python
python: 
- '2.7'

deploy: 
  provider: pypi
  user: bars-travis
  password: 
    secure: lxyj6xiKcSAS0ic0lV/AA8dciniVcEPxqHu4QIr4vx2T2vYAHElD0m63CD0LR+sL5KLCfZ4g0wwimzoIgMmuDcu+RIbE35Knobv0OK3H38mbT5M9theSsfjjhRY5DpQo0nhMFwW6UqIjtFwgEd8COxBmfA+cXPKLY+rLujngfyc=
  on: 
    tags: true
  distributions: sdist

notifications:
  email:
    recipients:
    - dev-py@bars-open.ru
