python: 
- "2.7"
script: true
language: python
notifications: 
  hipchat: 
    template: 
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    rooms: 
    - b7098c17bc3283dc7ca388b68e3ca3@m3
    format: html
deploy: 
  password: 
    secure: lxyj6xiKcSAS0ic0lV/AA8dciniVcEPxqHu4QIr4vx2T2vYAHElD0m63CD0LR+sL5KLCfZ4g0wwimzoIgMmuDcu+RIbE35Knobv0OK3H38mbT5M9theSsfjjhRY5DpQo0nhMFwW6UqIjtFwgEd8COxBmfA+cXPKLY+rLujngfyc=
  on: 
    all_branches: true
    tags: true
  user: bars-travis
  distributions: sdist
  provider: pypi
install: true
